CONFIG = {
    "device": "cuda:0",
    "runs": 1,
    "e_hidden": 0,
    "g_hidden": 0,
    "n_hidden": 512,
    "n_layers": 3,
    "activation": "relu",
    "dropout": 0.2,
    "norm_layer": "layer",
    "epochs": 200,
    "batch_size": 32,
    "stem_beta": 1,
    "branch_beta": 1,  # default: 0.5
    "keep_beta": 1,
    "cross_beta": 1,  # default: 0.5
    "last_hidden_dims": [512*4],
    "max_height": 1,
    "lambdaw": 0.2,
    "eps": 0.2,
    "temperature": 0.15,
    "pool_aggr_edge": "sum",
    "cluster_size_limit": 3,
    "perturbed": False,
    "soft_readout": True,
    "co": 4,
    "pow": 6,
    "global_pool_methods": ["mean"],
    "optimizer": {
        "lr": 1e-4,
        "betas": (0.95, 0.95),
        "eps": 1e-8,
    },
}